server:
  port: 8081

gg:
  jte:
    developmentMode: true

logging:
  level:
    org.springframework.web: DEBUG
    ru.mentee.power.crm: DEBUG
    root: debug
spring:
  jte:
    enabled: true
    content-type: text/html
